#######################################################################
# File name : docker-compose.yml
# Author : Olivier Galand (31/12/2021)
# Author email : galand.olivier.david@gmail.com
# Project : CashFactory
# Project repository : https://github.com/OlivierGaland/CashFactory
# 
# Docker-compose file of CashFactory
#######################################################################
version: '3.5'

services:
    #Start of Portainer + Webserver section :
    # Web GUI with quicklinks to apps dashboards and help : connect to your device port 80 (Webserver)
    # Container management and monitoring : connect to your device port 9000 (Portainer)
    Webserver:
        image: fnichol/uhttpd
        volumes:
            - ./www:/www
        ports:
            - 80:80
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.10
    Portainer:
        image: portainer/portainer-ce:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        ports:
            - 8000:8000
            - 9000:9000
            - 9443:9443
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.11
    #End of Portainer + Webserver section

   

    #Start of HoneyGain section (remove this if HoneyGain not wanted)
    # variables to define in .env file :
    # HONEYGAIN_EMAIL : Your Honeygain account email
    # HONEYGAIN_PASSWD : Your Honeygain account password 
    # DEVICE_NAME : This computer name (for display on dashboard)
    Honeygain:
        depends_on:
            - Portainer
            - Webserver
        image: honeygain/honeygain
        command: -tou-accept -email $HONEYGAIN_EMAIL -pass '$HONEYGAIN_PASSWD' -device $DEVICE_NAME
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.30
    #End of HoneyGain section

  



volumes:
    portainer_data:
    earnapp-data:

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16
